apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        #volumeMounts:
        #- name: homepage
        #  mountPath: "/var/www/html"
      #volumes:
      #  - name: homepage
      #    configMap: 
      #      name: homepage
      #      items:
      #      - key: index.html
      #        path: index.html
