apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    name: whoami
spec:
  containers:
  - name: whoami
    image: containous/whoami
    resources:
      limits:
        memory: "32Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
